In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
Path = 'drive/My Drive/datasets'

In [3]:
import pandas as pd

# Trying reading the file with 'latin-1' encoding
df = pd.read_csv(Path+'/yield_df.csv')

In [4]:
print("show first 20 rows")
print(df.head(20))

show first 20 rows
    Unnamed: 0     Area         Item  Year  hg/ha_yield  \
0            0  Albania        Maize  1990        36613
1            1  Albania     Potatoes  1990        66667
2            2  Albania  Rice, paddy  1990        23333
3            3  Albania      Sorghum  1990        12500
4            4  Albania     Soybeans  1990         7000
5            5  Albania        Wheat  1990        30197
6            6  Albania        Maize  1991        29068
7            7  Albania     Potatoes  1991        77818
8            8  Albania  Rice, paddy  1991        28538
9            9  Albania      Sorghum  1991         6667
10          10  Albania     Soybeans  1991         6066
11          11  Albania        Wheat  1991        20698
12          12  Albania        Maize  1992        24876
13          13  Albania     Potatoes  1992        82920
14          14  Albania  Rice, paddy  1992        40000
15          15  Albania      Sorghum  1992         3747
16          16  Albania     Soybeans  1992         4507
17          17  Albania        Wheat  1992        24388
18          18  Albania        Maize  1993        24185
19          19  Albania     Potatoes  1993        98446

    average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp
0                          1485.0              121.0     16.37
1                          1485.0              121.0     16.37
2                          1485.0              121.0     16.37
3                          1485.0              121.0     16.37
4                          1485.0              121.0     16.37
5                          1485.0              121.0     16.37
6                          1485.0              121.0     15.36
7                          1485.0              121.0     15.36
8                          1485.0              121.0     15.36
9                          1485.0              121.0     15.36
10                         1485.0              121.0     15.36
11                         1485.0              121.0     15.36
12                         1485.0              121.0     16.06
13                         1485.0              121.0     16.06
14                         1485.0              121.0     16.06
15                         1485.0              121.0     16.06
16                         1485.0              121.0     16.06
17                         1485.0              121.0     16.06
18                         1485.0              121.0     16.05
19                         1485.0              121.0     16.05

In [5]:
print("show last 20 rows")
print(df.tail(20))

show last 20 rows
       Unnamed: 0      Area            Item  Year  hg/ha_yield  \
28222       28222  Zimbabwe         Sorghum  2011         2267
28223       28223  Zimbabwe        Soybeans  2011        12054
28224       28224  Zimbabwe  Sweet potatoes  2011        21953
28225       28225  Zimbabwe           Wheat  2011        26274
28226       28226  Zimbabwe         Cassava  2012        47010
28227       28227  Zimbabwe           Maize  2012         7912
28228       28228  Zimbabwe        Potatoes  2012       171875
28229       28229  Zimbabwe     Rice, paddy  2012        22581
28230       28230  Zimbabwe         Sorghum  2012         2046
28231       28231  Zimbabwe        Soybeans  2012        15300
28232       28232  Zimbabwe  Sweet potatoes  2012        22222
28233       28233  Zimbabwe           Wheat  2012        24420
28234       28234  Zimbabwe         Cassava  2013        46000
28235       28235  Zimbabwe           Maize  2013         7449
28236       28236  Zimbabwe        Potatoes  2013       165714
28237       28237  Zimbabwe     Rice, paddy  2013        22581
28238       28238  Zimbabwe         Sorghum  2013         3066
28239       28239  Zimbabwe        Soybeans  2013        13142
28240       28240  Zimbabwe  Sweet potatoes  2013        22222
28241       28241  Zimbabwe           Wheat  2013        22888

       average_rain_fall_mm_per_year  pesticides_tonnes  avg_temp
28222                          657.0            3340.35     20.78
28223                          657.0            3340.35     20.78
28224                          657.0            3340.35     20.78
28225                          657.0            3340.35     20.78
28226                          657.0            3375.53     20.52
28227                          657.0            3375.53     20.52
28228                          657.0            3375.53     20.52
28229                          657.0            3375.53     20.52
28230                          657.0            3375.53     20.52
28231                          657.0            3375.53     20.52
28232                          657.0            3375.53     20.52
28233                          657.0            3375.53     20.52
28234                          657.0            2550.07     19.76
28235                          657.0            2550.07     19.76
28236                          657.0            2550.07     19.76
28237                          657.0            2550.07     19.76
28238                          657.0            2550.07     19.76
28239                          657.0            2550.07     19.76
28240                          657.0            2550.07     19.76
28241                          657.0            2550.07     19.76

In [6]:
print("show all columns")
print(df.columns)

show all columns
Index(['Unnamed: 0', 'Area', 'Item', 'Year', 'hg/ha_yield',
       'average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp'],
      dtype='object')

In [7]:
print("show all rows")
print(df.index)

show all rows
RangeIndex(start=0, stop=28242, step=1)

In [8]:
print("show all values")
print(df.values)

show all values
[[0 'Albania' 'Maize' ... 1485.0 121.0 16.37]
 [1 'Albania' 'Potatoes' ... 1485.0 121.0 16.37]
 [2 'Albania' 'Rice, paddy' ... 1485.0 121.0 16.37]
 ...
 [28239 'Zimbabwe' 'Soybeans' ... 657.0 2550.07 19.76]
 [28240 'Zimbabwe' 'Sweet potatoes' ... 657.0 2550.07 19.76]
 [28241 'Zimbabwe' 'Wheat' ... 657.0 2550.07 19.76]]